version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mck2022
      POSTGRES_DB: booking_hotel

#  api:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    volumes:
#      - .:/usr/src/app
#    command: npm run start
#    ports:
#      - "3000:3000"
